# name: Run Pre-Commit Hooks

# on:
#   pull_request:
#     branches: [main]
#     types: [opened, synchronize, reopened]
#   workflow_dispatch:

# jobs:
#   pre-commit:
#     name: Run Pre-Commit Hooks
#     runs-on: [windows-latest]

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v4

#       - name: Set up Python
#         uses: actions/setup-python@v5
#         with:
#           python-version: '3.11'

#       - name: Install Chocolatey (if not already installed)
#         run: |
#           if (!(Get-Command choco -ErrorAction SilentlyContinue)) {
#             Set-ExecutionPolicy Bypass -Scope Process -Force
#             [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
#             iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
#           }

#       - name: Install TFLint using Chocolatey
#         run: choco install tflint -y

#       - name: Install Terraform using Chocolatey
#         run: choco install terraform -y

#       - name: Ensure Chocolatey-installed tools are in PATH
#         shell: pwsh
#         run: |
#           $env:Path += ";C:\ProgramData\chocolatey\bin"
#           Write-Host "TFLint path: $(Get-Command tflint).Source"
#           Write-Host "Terraform path: $(Get-Command terraform).Source"

#       - name: Check Terraform and tflint versions
#         run: |
#           tflint --init
#           terraform version
#           tflint --version

#       - name: Install pre-commit
#         run: pip install pre-commit

#       - name: Run pre-commit hooks
#         run: pre-commit run --all-files

# ---------------------------------------------------------------------------------------

name: Run Pre-Commit Hooks

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  pre-commit:
    name: Run Pre-Commit Hooks
    runs-on: [windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.7"
          terraform_wrapper: false

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: "v0.48.0"

      - name: Verify tools are in PATH
        shell: pwsh
        run: |
          Write-Host "TFLint path: $(Get-Command tflint).Source"
          Write-Host "Terraform path: $(Get-Command terraform).Source"

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run pre-commit hooks
        shell: bash
        run: pre-commit run --all-files
